### ISSUE TITLE
This stable for 10.4

### ISSUE THREAD

**Issue by Zillion01** [Megafry/t3ddy#1]
Hey thanks a lot, for publishing this update for 10.4. Is this stable?

**Comment by Zillion01** [comment]
Hey thanks a lot, for publishing this update for 10.4. Is this stable?

**Comment by Megafry** [comment]
Hi
We use this version on several TYPO3 installation

If the Gridelements are empty after the core Update, execute this query:
```sql
UPDATE `tt_content` SET `colPos` = '-1' WHERE `tx_gridelements_container` > '0'
```

**Comment by Zillion01** [comment]
Great! Thanks!!
